/*  */
package com.packetsniffer.emenegal.packetsniffer.database;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

// Start of user code additional import for PacketModel
// End of user code

/** 
  *  
  */ 
@DatabaseTable(tableName = "netActivity")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, 
                  property  = "_id",
				  scope = PacketModel.class)
public class PacketModel {

	public static Log log = LogFactory.getLog(PacketModel.class);

	public static final String XML_NETACTIVITY = "NETACTIVITY";
	public static final String XML_ATT_ID = "id";
	public static final String XML_ATT_DATE = "date";
	public static final String XML_ATT_APPLICATION = "application";
	public static final String XML_ATT_HOSTNAME = "hostname";
	public static final String XML_ATT_IPDESTINATION = "ipDestination";
	public static final String XML_ATT_USERID = "userId";
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;

	/**
     * dbHelper used to autorefresh values and doing queries
     * must be set other wise most getter will return proxy that will need to be refreshed
	 */
	@JsonIgnore
	protected PacketModel _contextDB = null;

	/**
	 * object created from DB may need to be updated from the DB for being fully navigable
	 */
	

	@DatabaseField
	protected java.util.Date date;

	/** application that requested the url */ 
	@DatabaseField
	protected java.lang.String application;

	@DatabaseField
	protected java.lang.String hostname;

	@DatabaseField
	protected java.lang.String ipDestination;

	@DatabaseField
	protected java.lang.String userId;
	

	// Start of user code PacketModel additional user properties
	// End of user code
	
	public PacketModel() {} // needed by ormlite
	public PacketModel(java.util.Date date, java.lang.String application, java.lang.String hostname, java.lang.String ipDestination, java.lang.String userId) {
		super();
		this.date = date;
		this.application = application;
		this.hostname = hostname;
		this.ipDestination = ipDestination;
		this.userId = userId;
	} 

	public int get_id() {
		return _id;
	}
	@JsonProperty
	public void set_id(int id) {
		this._id = id;
	}

	public PacketModel getContextDB(){
		return _contextDB;
	}
	@JsonIgnore
	public void setContextDB(PacketModel contextDB){
		this._contextDB = contextDB;
	}

	public java.util.Date getDate() {
		return this.date;
	}
	@JsonProperty
	public void setDate(java.util.Date date) {
		this.date = date;
	}
	public java.lang.String getApplication() {
		return this.application;
	}
	@JsonProperty
	public void setApplication(java.lang.String application) {
		this.application = application;
	}
	public java.lang.String getHostname() {
		return this.hostname;
	}
	@JsonProperty
	public void setHostname(java.lang.String hostname) {
		this.hostname = hostname;
	}
	public java.lang.String getIpDestination() {
		return this.ipDestination;
	}
	@JsonProperty
	public void setIpDestination(java.lang.String ipDestination) {
		this.ipDestination = ipDestination;
	}
	public java.lang.String getUserId() {
		return this.userId;
	}
	@JsonProperty
	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}
}
